//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien_DA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FITHOU_LIB_DeXuatTheLoai
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string TenTheLoai { get; set; }
        public string LyDoDeXuat { get; set; }
        public Nullable<System.DateTime> NgayDeXuat { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    }
}
