//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien_DA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FITHOU_LIB_BaiDang
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> SoLuotXem { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    }
}
